version: '3.8'

services:
  # Redis service with Alpine image
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  # Redis UI service (RedisInsight) with Alpine-based image
  redis-ui:
    image: redisinsight/redisinsight:latest
    container_name: redis-ui
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend

  # PostgreSQL service with Alpine image
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # PgAdmin service with Alpine-based image
  pgadmin:
    image: dpage/pgadmin4:alpine
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
